import gra
import copy


ga1 = gra.Grafo(False).dorogov(150)
gra.Grafo(False).saveGraph(ga1,1)
ga11 = copy.deepcopy(ga1)
ga111 = copy.deepcopy(ga1)
ga2 = gra.Grafo(False).prim(ga1)
ga3 = gra.Grafo(False).kruskalInverso(ga11)
ga4 = gra.Grafo(False).Kruskal(ga111)
gra.Grafo(False).saveGraph(ga2,2)
gra.Grafo(False).saveGraph(ga3,3)
gra.Grafo(False).saveGraph(ga4,4)
#ga2 = gra.Grafo(False).dijkstra(50,ga1)
#gra.Grafo(False).saveGraph2(ga1,ga2)
#ga2 = gra.Grafo(False).BFS(3,ga1)
#gra.Grafo(False).saveGraph(ga2)
#revisado = set()
#a = []
#ga2 = gra.Grafo(False).DFSRecursive(3,ga1,revisado,a)
#gra.Grafo(False).saveGraph(ga2)
#ga2 = gra.Grafo(False).DFSIterative(3,ga1)
#gra.Grafo(False).saveGraph(ga2)

#ga1 = gra.Grafo(False).dorogov(100)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).dorogov(500)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).grafoMalla(15,15)
#gra.Grafo(False).saveGraph(ga1,1)
#ga11 = copy.deepcopy(ga1)
#ga111 = copy.deepcopy(ga1)
#ga2 = gra.Grafo(False).prim(ga1)
#ga3 = gra.Grafo(False).kruskalInverso(ga11)
#ga4 = gra.Grafo(False).Kruskal(ga111)
#gra.Grafo(False).saveGraph(ga2,2)
#gra.Grafo(False).saveGraph(ga3,3)
#gra.Grafo(False).saveGraph(ga4,4)
#ga2 = gra.Grafo(False).BFS(3,ga1)
#gra.Grafo(False).saveGraph(ga2)
#revisado = set()
#a = []
#ga2 = gra.Grafo(False).DFSRecursive(3,ga1,revisado,a)
#gra.Grafo(False).saveGraph(ga2)
#ga2 = gra.Grafo(False).DFSIterative(3,ga1)
#gra.Grafo(False).saveGraph(ga2)

#ga1 = gra.Grafo(False).grafoMalla(5,5)
#gra.Grafo(False).saveGraph(ga1)
#ga2 = gra.Grafo(False).dijkstra(10,ga1)
#gra.Grafo(False).saveGraph2(ga1,ga2)

#ga1 = gra.Grafo(False).grafoMalla(25,25)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).barasi(150,5)
#gra.Grafo(False).saveGraph(ga1,1)
#ga11 = copy.deepcopy(ga1)
#ga111 = copy.deepcopy(ga1)
#ga2 = gra.Grafo(False).prim(ga1)
#ga3 = gra.Grafo(False).kruskalInverso(ga11)
#ga4 = gra.Grafo(False).Kruskal(ga111)
#gra.Grafo(False).saveGraph(ga2,2)
#gra.Grafo(False).saveGraph(ga3,3)
#gra.Grafo(False).saveGraph(ga4,4)
#ga2 = gra.Grafo(False).dijkstra(30,ga1)
#gra.Grafo(False).saveGraph2(ga1,ga2)
#ga2 = gra.Grafo(False).BFS(3,ga1)
#gra.Grafo(False).saveGraph(ga2)
#revisado = set()
#a = []
#ga2 = gra.Grafo(False).DFSRecursive(3,ga1,revisado,a)
#gra.Grafo(False).saveGraph(ga2)
#ga2 = gra.Grafo(False).DFSIterative(3,ga1)
#gra.Grafo(False).saveGraph(ga2)

#ga1 = gra.Grafo(False).barasi(100,5)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).barasi(500,5)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).geografica(150,.3)
#gra.Grafo(False).saveGraph(ga1,1)
#ga11 = copy.deepcopy(ga1)
#ga111 = copy.deepcopy(ga1)
#ga2 = gra.Grafo(False).prim(ga1)
#ga3 = gra.Grafo(False).kruskalInverso(ga11)
#ga4 = gra.Grafo(False).Kruskal(ga111)
#gra.Grafo(False).saveGraph(ga2,2)
#gra.Grafo(False).saveGraph(ga3,3)
#gra.Grafo(False).saveGraph(ga4,4)
#ga2 = gra.Grafo(False).dijkstra(25,ga1)
#gra.Grafo(False).saveGraph2(ga1,ga2)
#ga2 = gra.Grafo(False).BFS(10,ga1)
#gra.Grafo(False).saveGraph(ga2)
#revisado = set()
#a = []
#ga2 = gra.Grafo(False).DFSRecursive(3,ga1,revisado,a)
#gra.Grafo(False).saveGraph(ga2)
#ga2 = gra.Grafo(False).DFSIterative(3,ga1)
#gra.Grafo(False).saveGraph(ga2)


#ga1 = gra.Grafo(False).geografica(100,.7)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).geografica(500,.7)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).gilbert(150,.7)
#gra.Grafo(False).saveGraph(ga1,1)
#ga11 = copy.deepcopy(ga1)
#ga111 = copy.deepcopy(ga1)
#ga2 = gra.Grafo(False).prim(ga1)
#ga3 = gra.Grafo(False).kruskalInverso(ga11)
#ga4 = gra.Grafo(False).Kruskal(ga111)
#gra.Grafo(False).saveGraph(ga2,2)
#gra.Grafo(False).saveGraph(ga3,3)
#gra.Grafo(False).saveGraph(ga4,4)
#ga2 = gra.Grafo(False).dijkstra(50,ga1)
#gra.Grafo(False).saveGraph2(ga1,ga2)
#ga2 = gra.Grafo(False).BFS(10,ga1)
#gra.Grafo(False).saveGraph(ga2)
#revisado = set()
#a = []
#ga2 = gra.Grafo(False).DFSRecursive(3,ga1,revisado,a)
#gra.Grafo(False).saveGraph(ga2)
#ga2 = gra.Grafo(False).DFSIterative(3,ga1)
#gra.Grafo(False).saveGraph(ga2)

#ga1 = gra.Grafo(False).gilbert(100,.5)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).gilbert(500,.5)
#gra.Grafo(False).saveGraph(ga1)

#ga1 = gra.Grafo(False).erdosRenyi(10,30)
#gra.Grafo(False).saveGraph(ga1,1)
#ga11 = copy.deepcopy(ga1)
#ga111 = copy.deepcopy(ga1)
#ga2 = gra.Grafo(False).prim(ga1)
#ga3 = gra.Grafo(False).kruskalInverso(ga11)
#ga4 = gra.Grafo(False).Kruskal(ga111)
#gra.Grafo(False).saveGraph(ga2,2)
#gra.Grafo(False).saveGraph(ga3,3)
#gra.Grafo(False).saveGraph(ga4,4)
#ga2 = gra.Grafo(False).dijkstra(100,ga1)
#gra.Grafo(False).saveGraph2(ga1,ga2)
#ga2 = gra.Grafo(False).BFS(10,ga1)
#gra.Grafo(False).saveGraph(ga2)
#revisado = set()
#a = []
#ga2 = gra.Grafo(False).DFSRecursive(3,ga1,revisado,a)
#gra.Grafo(False).saveGraph(ga2)
#ga2 = gra.Grafo(False).DFSIterative(3,ga1)
#gra.Grafo(False).saveGraph(ga2)